[package]
name = "remote-core"
edition.workspace = true
rust-version.workspace = true

[dependencies]
serde.workspace = true
serde_json.workspace = true
dirs.workspace = true
uuid.workspace = true
tex-domain = { path = "../tex-domain" }
build-core = { path = "../build-core" }

[target.'cfg(unix)'.dependencies]
libc.workspace = true
