//! Port of `Packages/TexCore/Sources/LanguageCore/Symbols.swift` — the
//! TeXifier-style palette catalogue. Entries and ordering are identical to
//! `TexSymbolCatalogue.symbols` so both platforms render the same grid.

use serde::{Deserialize, Serialize};

/// Palette categories — `title_key` resolves the display name through
/// `Localizable.strings` like the Swift `titleKey`.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub enum SymbolCategory {
    GreekLetters,
    BinaryRelations,
    BinaryOperators,
    BigOperators,
    Arrows,
    Delimiters,
    LargeDelimiters,
    MiscMaths,
    TextModeSymbols,
    AmsDelimiters,
    AmsGreekHebrew,
    AmsBinaryOperators,
    AmsBinaryRelations,
    AmsArrows,
}

impl SymbolCategory {
    /// Declaration order — the picker's row order on both platforms.
    pub const ALL: &'static [SymbolCategory] = &[
        Self::GreekLetters,
        Self::BinaryRelations,
        Self::BinaryOperators,
        Self::BigOperators,
        Self::Arrows,
        Self::Delimiters,
        Self::LargeDelimiters,
        Self::MiscMaths,
        Self::TextModeSymbols,
        Self::AmsDelimiters,
        Self::AmsGreekHebrew,
        Self::AmsBinaryOperators,
        Self::AmsBinaryRelations,
        Self::AmsArrows,
    ];

    /// `Localizable.strings` key for the category's picker label.
    pub fn title_key(self) -> &'static str {
        match self {
            Self::GreekLetters => "editor.symbol_cat_greek",
            Self::BinaryRelations => "editor.symbol_cat_binary_relations",
            Self::BinaryOperators => "editor.symbol_cat_binary_operators",
            Self::BigOperators => "editor.symbol_cat_big_operators",
            Self::Arrows => "editor.symbol_cat_arrows",
            Self::Delimiters => "editor.symbol_cat_delimiters",
            Self::LargeDelimiters => "editor.symbol_cat_large_delimiters",
            Self::MiscMaths => "editor.symbol_cat_misc_math",
            Self::TextModeSymbols => "editor.symbol_cat_text_mode",
            Self::AmsDelimiters => "editor.symbol_cat_ams_delimiters",
            Self::AmsGreekHebrew => "editor.symbol_cat_ams_greek_hebrew",
            Self::AmsBinaryOperators => "editor.symbol_cat_ams_binary_operators",
            Self::AmsBinaryRelations => "editor.symbol_cat_ams_binary_relations",
            Self::AmsArrows => "editor.symbol_cat_ams_arrows",
        }
    }
}

/// One palette cell: the rendered `glyph` shown large, the LaTeX `command`
/// inserted at the caret on click.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub struct TexSymbol {
    pub glyph: &'static str,
    pub command: &'static str,
    pub category: SymbolCategory,
}

const fn s(glyph: &'static str, command: &'static str, category: SymbolCategory) -> TexSymbol {
    TexSymbol {
        glyph,
        command,
        category,
    }
}

/// The static symbol catalogue — standard LaTeX plus the AMS groups, in a
/// fixed order so the palette renders identically on both platforms.
pub static TEX_SYMBOLS: &[TexSymbol] = &[
    // ── Greek letters ──
    s("α", "\\alpha", SymbolCategory::GreekLetters),
    s("β", "\\beta", SymbolCategory::GreekLetters),
    s("γ", "\\gamma", SymbolCategory::GreekLetters),
    s("δ", "\\delta", SymbolCategory::GreekLetters),
    s("ϵ", "\\epsilon", SymbolCategory::GreekLetters),
    s("ε", "\\varepsilon", SymbolCategory::GreekLetters),
    s("ζ", "\\zeta", SymbolCategory::GreekLetters),
    s("η", "\\eta", SymbolCategory::GreekLetters),
    s("θ", "\\theta", SymbolCategory::GreekLetters),
    s("ϑ", "\\vartheta", SymbolCategory::GreekLetters),
    s("ι", "\\iota", SymbolCategory::GreekLetters),
    s("κ", "\\kappa", SymbolCategory::GreekLetters),
    s("λ", "\\lambda", SymbolCategory::GreekLetters),
    s("μ", "\\mu", SymbolCategory::GreekLetters),
    s("ν", "\\nu", SymbolCategory::GreekLetters),
    s("ξ", "\\xi", SymbolCategory::GreekLetters),
    s("π", "\\pi", SymbolCategory::GreekLetters),
    s("ϖ", "\\varpi", SymbolCategory::GreekLetters),
    s("ρ", "\\rho", SymbolCategory::GreekLetters),
    s("ϱ", "\\varrho", SymbolCategory::GreekLetters),
    s("σ", "\\sigma", SymbolCategory::GreekLetters),
    s("ς", "\\varsigma", SymbolCategory::GreekLetters),
    s("τ", "\\tau", SymbolCategory::GreekLetters),
    s("υ", "\\upsilon", SymbolCategory::GreekLetters),
    s("φ", "\\phi", SymbolCategory::GreekLetters),
    s("ϕ", "\\varphi", SymbolCategory::GreekLetters),
    s("χ", "\\chi", SymbolCategory::GreekLetters),
    s("ψ", "\\psi", SymbolCategory::GreekLetters),
    s("ω", "\\omega", SymbolCategory::GreekLetters),
    s("Γ", "\\Gamma", SymbolCategory::GreekLetters),
    s("Δ", "\\Delta", SymbolCategory::GreekLetters),
    s("Θ", "\\Theta", SymbolCategory::GreekLetters),
    s("Λ", "\\Lambda", SymbolCategory::GreekLetters),
    s("Ξ", "\\Xi", SymbolCategory::GreekLetters),
    s("Π", "\\Pi", SymbolCategory::GreekLetters),
    s("Σ", "\\Sigma", SymbolCategory::GreekLetters),
    s("Υ", "\\Upsilon", SymbolCategory::GreekLetters),
    s("Φ", "\\Phi", SymbolCategory::GreekLetters),
    s("Ψ", "\\Psi", SymbolCategory::GreekLetters),
    s("Ω", "\\Omega", SymbolCategory::GreekLetters),
    // ── Binary relations ──
    s("≤", "\\leq", SymbolCategory::BinaryRelations),
    s("≥", "\\geq", SymbolCategory::BinaryRelations),
    s("≠", "\\neq", SymbolCategory::BinaryRelations),
    s("≈", "\\approx", SymbolCategory::BinaryRelations),
    s("≡", "\\equiv", SymbolCategory::BinaryRelations),
    s("≅", "\\cong", SymbolCategory::BinaryRelations),
    s("≃", "\\simeq", SymbolCategory::BinaryRelations),
    s("∼", "\\sim", SymbolCategory::BinaryRelations),
    s("∝", "\\propto", SymbolCategory::BinaryRelations),
    s("≐", "\\doteq", SymbolCategory::BinaryRelations),
    s("≍", "\\asymp", SymbolCategory::BinaryRelations),
    s("≺", "\\prec", SymbolCategory::BinaryRelations),
    s("≻", "\\succ", SymbolCategory::BinaryRelations),
    s("⪯", "\\preceq", SymbolCategory::BinaryRelations),
    s("⪰", "\\succeq", SymbolCategory::BinaryRelations),
    s("≪", "\\ll", SymbolCategory::BinaryRelations),
    s("≫", "\\gg", SymbolCategory::BinaryRelations),
    s("⊂", "\\subset", SymbolCategory::BinaryRelations),
    s("⊃", "\\supset", SymbolCategory::BinaryRelations),
    s("⊆", "\\subseteq", SymbolCategory::BinaryRelations),
    s("⊇", "\\supseteq", SymbolCategory::BinaryRelations),
    s("⊏", "\\sqsubset", SymbolCategory::BinaryRelations),
    s("⊐", "\\sqsupset", SymbolCategory::BinaryRelations),
    s("⊑", "\\sqsubseteq", SymbolCategory::BinaryRelations),
    s("⊒", "\\sqsupseteq", SymbolCategory::BinaryRelations),
    s("∈", "\\in", SymbolCategory::BinaryRelations),
    s("∋", "\\ni", SymbolCategory::BinaryRelations),
    s("∉", "\\notin", SymbolCategory::BinaryRelations),
    s("⊢", "\\vdash", SymbolCategory::BinaryRelations),
    s("⊣", "\\dashv", SymbolCategory::BinaryRelations),
    s("⊨", "\\models", SymbolCategory::BinaryRelations),
    s("⊥", "\\perp", SymbolCategory::BinaryRelations),
    s("∣", "\\mid", SymbolCategory::BinaryRelations),
    s("∥", "\\parallel", SymbolCategory::BinaryRelations),
    s("⌣", "\\smile", SymbolCategory::BinaryRelations),
    s("⌢", "\\frown", SymbolCategory::BinaryRelations),
    s("⋈", "\\bowtie", SymbolCategory::BinaryRelations),
    // ── Binary operators ──
    s("±", "\\pm", SymbolCategory::BinaryOperators),
    s("∓", "\\mp", SymbolCategory::BinaryOperators),
    s("×", "\\times", SymbolCategory::BinaryOperators),
    s("÷", "\\div", SymbolCategory::BinaryOperators),
    s("·", "\\cdot", SymbolCategory::BinaryOperators),
    s("∪", "\\cup", SymbolCategory::BinaryOperators),
    s("∩", "\\cap", SymbolCategory::BinaryOperators),
    s("⊔", "\\sqcup", SymbolCategory::BinaryOperators),
    s("⊓", "\\sqcap", SymbolCategory::BinaryOperators),
    s("∨", "\\vee", SymbolCategory::BinaryOperators),
    s("∧", "\\wedge", SymbolCategory::BinaryOperators),
    s("⊕", "\\oplus", SymbolCategory::BinaryOperators),
    s("⊖", "\\ominus", SymbolCategory::BinaryOperators),
    s("⊗", "\\otimes", SymbolCategory::BinaryOperators),
    s("⊘", "\\oslash", SymbolCategory::BinaryOperators),
    s("⊙", "\\odot", SymbolCategory::BinaryOperators),
    s("∘", "\\circ", SymbolCategory::BinaryOperators),
    s("∗", "\\ast", SymbolCategory::BinaryOperators),
    s("⋆", "\\star", SymbolCategory::BinaryOperators),
    s("†", "\\dagger", SymbolCategory::BinaryOperators),
    s("‡", "\\ddagger", SymbolCategory::BinaryOperators),
    s("∖", "\\setminus", SymbolCategory::BinaryOperators),
    s("◁", "\\triangleleft", SymbolCategory::BinaryOperators),
    s("▷", "\\triangleright", SymbolCategory::BinaryOperators),
    s("○", "\\bigcirc", SymbolCategory::BinaryOperators),
    s("∙", "\\bullet", SymbolCategory::BinaryOperators),
    s("⊎", "\\uplus", SymbolCategory::BinaryOperators),
    s("⨿", "\\amalg", SymbolCategory::BinaryOperators),
    s("⋄", "\\diamond", SymbolCategory::BinaryOperators),
    s("≀", "\\wr", SymbolCategory::BinaryOperators),
    // ── Big operators ──
    s("∑", "\\sum", SymbolCategory::BigOperators),
    s("∏", "\\prod", SymbolCategory::BigOperators),
    s("∐", "\\coprod", SymbolCategory::BigOperators),
    s("∫", "\\int", SymbolCategory::BigOperators),
    s("∮", "\\oint", SymbolCategory::BigOperators),
    s("⋃", "\\bigcup", SymbolCategory::BigOperators),
    s("⋂", "\\bigcap", SymbolCategory::BigOperators),
    s("⨆", "\\bigsqcup", SymbolCategory::BigOperators),
    s("⋁", "\\bigvee", SymbolCategory::BigOperators),
    s("⋀", "\\bigwedge", SymbolCategory::BigOperators),
    s("⨁", "\\bigoplus", SymbolCategory::BigOperators),
    s("⨂", "\\bigotimes", SymbolCategory::BigOperators),
    s("⨀", "\\bigodot", SymbolCategory::BigOperators),
    s("⨄", "\\biguplus", SymbolCategory::BigOperators),
    // ── Arrows ──
    s("←", "\\leftarrow", SymbolCategory::Arrows),
    s("→", "\\rightarrow", SymbolCategory::Arrows),
    s("↑", "\\uparrow", SymbolCategory::Arrows),
    s("↓", "\\downarrow", SymbolCategory::Arrows),
    s("↕", "\\updownarrow", SymbolCategory::Arrows),
    s("⇐", "\\Leftarrow", SymbolCategory::Arrows),
    s("⇒", "\\Rightarrow", SymbolCategory::Arrows),
    s("⇑", "\\Uparrow", SymbolCategory::Arrows),
    s("⇓", "\\Downarrow", SymbolCategory::Arrows),
    s("⇕", "\\Updownarrow", SymbolCategory::Arrows),
    s("↔", "\\leftrightarrow", SymbolCategory::Arrows),
    s("⇔", "\\Leftrightarrow", SymbolCategory::Arrows),
    s("↦", "\\mapsto", SymbolCategory::Arrows),
    s("⟵", "\\longleftarrow", SymbolCategory::Arrows),
    s("⟶", "\\longrightarrow", SymbolCategory::Arrows),
    s("⟸", "\\Longleftarrow", SymbolCategory::Arrows),
    s("⟹", "\\Longrightarrow", SymbolCategory::Arrows),
    s("⟷", "\\longleftrightarrow", SymbolCategory::Arrows),
    s("⟺", "\\Longleftrightarrow", SymbolCategory::Arrows),
    s("⟼", "\\longmapsto", SymbolCategory::Arrows),
    s("↩", "\\hookleftarrow", SymbolCategory::Arrows),
    s("↪", "\\hookrightarrow", SymbolCategory::Arrows),
    s("↼", "\\leftharpoonup", SymbolCategory::Arrows),
    s("↽", "\\leftharpoondown", SymbolCategory::Arrows),
    s("⇀", "\\rightharpoonup", SymbolCategory::Arrows),
    s("⇁", "\\rightharpoondown", SymbolCategory::Arrows),
    s("⇌", "\\rightleftharpoons", SymbolCategory::Arrows),
    s("↗", "\\nearrow", SymbolCategory::Arrows),
    s("↘", "\\searrow", SymbolCategory::Arrows),
    s("↖", "\\nwarrow", SymbolCategory::Arrows),
    s("↙", "\\swarrow", SymbolCategory::Arrows),
    s("⇝", "\\leadsto", SymbolCategory::Arrows),
    s("←", "\\gets", SymbolCategory::Arrows),
    s("→", "\\to", SymbolCategory::Arrows),
    // ── Delimiters ──
    s("(", "(", SymbolCategory::Delimiters),
    s(")", ")", SymbolCategory::Delimiters),
    s("[", "[", SymbolCategory::Delimiters),
    s("]", "]", SymbolCategory::Delimiters),
    s("{", "\\{", SymbolCategory::Delimiters),
    s("}", "\\}", SymbolCategory::Delimiters),
    s("⟨", "\\langle", SymbolCategory::Delimiters),
    s("⟩", "\\rangle", SymbolCategory::Delimiters),
    s("|", "|", SymbolCategory::Delimiters),
    s("‖", "\\|", SymbolCategory::Delimiters),
    s("⌈", "\\lceil", SymbolCategory::Delimiters),
    s("⌉", "\\rceil", SymbolCategory::Delimiters),
    s("⌊", "\\lfloor", SymbolCategory::Delimiters),
    s("⌋", "\\rfloor", SymbolCategory::Delimiters),
    s("/", "/", SymbolCategory::Delimiters),
    s("\\", "\\backslash", SymbolCategory::Delimiters),
    s("↑", "\\uparrow", SymbolCategory::Delimiters),
    s("↓", "\\downarrow", SymbolCategory::Delimiters),
    s("↕", "\\updownarrow", SymbolCategory::Delimiters),
    s("⇑", "\\Uparrow", SymbolCategory::Delimiters),
    s("⇓", "\\Downarrow", SymbolCategory::Delimiters),
    s("⇕", "\\Updownarrow", SymbolCategory::Delimiters),
    // ── Large delimiters ──
    s("()", "\\left( \\right)", SymbolCategory::LargeDelimiters),
    s("[]", "\\left[ \\right]", SymbolCategory::LargeDelimiters),
    s("{}", "\\left\\{ \\right\\}", SymbolCategory::LargeDelimiters),
    s("||", "\\left| \\right|", SymbolCategory::LargeDelimiters),
    s("‖‖", "\\left\\| \\right\\|", SymbolCategory::LargeDelimiters),
    s("⟨⟩", "\\left\\langle \\right\\rangle", SymbolCategory::LargeDelimiters),
    s("⌈⌉", "\\left\\lceil \\right\\rceil", SymbolCategory::LargeDelimiters),
    s("⌊⌋", "\\left\\lfloor \\right\\rfloor", SymbolCategory::LargeDelimiters),
    s("↑↓", "\\left\\uparrow \\right\\downarrow", SymbolCategory::LargeDelimiters),
    s("(", "\\bigl(", SymbolCategory::LargeDelimiters),
    s(")", "\\bigr)", SymbolCategory::LargeDelimiters),
    s("(", "\\Bigl(", SymbolCategory::LargeDelimiters),
    s(")", "\\Bigr)", SymbolCategory::LargeDelimiters),
    s("[", "\\bigl[", SymbolCategory::LargeDelimiters),
    s("]", "\\bigr]", SymbolCategory::LargeDelimiters),
    s("{", "\\bigl\\{", SymbolCategory::LargeDelimiters),
    s("}", "\\bigr\\}", SymbolCategory::LargeDelimiters),
    s("⟨", "\\bigl\\langle", SymbolCategory::LargeDelimiters),
    s("⟩", "\\bigr\\rangle", SymbolCategory::LargeDelimiters),
    s("|", "\\big|", SymbolCategory::LargeDelimiters),
    s("‖", "\\big\\|", SymbolCategory::LargeDelimiters),
    // ── Miscellaneous math ──
    s("∀", "\\forall", SymbolCategory::MiscMaths),
    s("∃", "\\exists", SymbolCategory::MiscMaths),
    s("∄", "\\nexists", SymbolCategory::MiscMaths),
    s("∅", "\\emptyset", SymbolCategory::MiscMaths),
    s("∞", "\\infty", SymbolCategory::MiscMaths),
    s("∂", "\\partial", SymbolCategory::MiscMaths),
    s("∇", "\\nabla", SymbolCategory::MiscMaths),
    s("ℵ", "\\aleph", SymbolCategory::MiscMaths),
    s("ℏ", "\\hbar", SymbolCategory::MiscMaths),
    s("ℓ", "\\ell", SymbolCategory::MiscMaths),
    s("℘", "\\wp", SymbolCategory::MiscMaths),
    s("ℜ", "\\Re", SymbolCategory::MiscMaths),
    s("ℑ", "\\Im", SymbolCategory::MiscMaths),
    s("′", "\\prime", SymbolCategory::MiscMaths),
    s("√", "\\surd", SymbolCategory::MiscMaths),
    s("⊤", "\\top", SymbolCategory::MiscMaths),
    s("⊥", "\\bot", SymbolCategory::MiscMaths),
    s("∠", "\\angle", SymbolCategory::MiscMaths),
    s("△", "\\triangle", SymbolCategory::MiscMaths),
    s("¬", "\\neg", SymbolCategory::MiscMaths),
    s("♭", "\\flat", SymbolCategory::MiscMaths),
    s("♮", "\\natural", SymbolCategory::MiscMaths),
    s("♯", "\\sharp", SymbolCategory::MiscMaths),
    s("♣", "\\clubsuit", SymbolCategory::MiscMaths),
    s("♢", "\\diamondsuit", SymbolCategory::MiscMaths),
    s("♡", "\\heartsuit", SymbolCategory::MiscMaths),
    s("♠", "\\spadesuit", SymbolCategory::MiscMaths),
    s("ı", "\\imath", SymbolCategory::MiscMaths),
    s("ȷ", "\\jmath", SymbolCategory::MiscMaths),
    // ── Text-mode symbols ──
    s("§", "\\S", SymbolCategory::TextModeSymbols),
    s("¶", "\\P", SymbolCategory::TextModeSymbols),
    s("†", "\\dag", SymbolCategory::TextModeSymbols),
    s("‡", "\\ddag", SymbolCategory::TextModeSymbols),
    s("©", "\\copyright", SymbolCategory::TextModeSymbols),
    s("£", "\\pounds", SymbolCategory::TextModeSymbols),
    s("¥", "\\textyen", SymbolCategory::TextModeSymbols),
    s("€", "\\texteuro", SymbolCategory::TextModeSymbols),
    s("™", "\\texttrademark", SymbolCategory::TextModeSymbols),
    s("®", "\\textregistered", SymbolCategory::TextModeSymbols),
    s("°", "\\textdegree", SymbolCategory::TextModeSymbols),
    s("…", "\\dots", SymbolCategory::TextModeSymbols),
    s("—", "\\textemdash", SymbolCategory::TextModeSymbols),
    s("–", "\\textendash", SymbolCategory::TextModeSymbols),
    s("‘", "\\textquoteleft", SymbolCategory::TextModeSymbols),
    s("’", "\\textquoteright", SymbolCategory::TextModeSymbols),
    s("“", "\\textquotedblleft", SymbolCategory::TextModeSymbols),
    s("”", "\\textquotedblright", SymbolCategory::TextModeSymbols),
    s("¡", "\\textexclamdown", SymbolCategory::TextModeSymbols),
    s("¿", "\\textquestiondown", SymbolCategory::TextModeSymbols),
    s("<", "\\textless", SymbolCategory::TextModeSymbols),
    s(">", "\\textgreater", SymbolCategory::TextModeSymbols),
    s("|", "\\textbar", SymbolCategory::TextModeSymbols),
    s("\\", "\\textbackslash", SymbolCategory::TextModeSymbols),
    s("~", "\\textasciitilde", SymbolCategory::TextModeSymbols),
    s("^", "\\textasciicircum", SymbolCategory::TextModeSymbols),
    s("_", "\\textunderscore", SymbolCategory::TextModeSymbols),
    s("#", "\\#", SymbolCategory::TextModeSymbols),
    s("$", "\\$", SymbolCategory::TextModeSymbols),
    s("%", "\\%", SymbolCategory::TextModeSymbols),
    s("&", "\\&", SymbolCategory::TextModeSymbols),
    s("{", "\\{", SymbolCategory::TextModeSymbols),
    s("}", "\\}", SymbolCategory::TextModeSymbols),
    // ── AMS delimiters ──
    s("⌜", "\\ulcorner", SymbolCategory::AmsDelimiters),
    s("⌝", "\\urcorner", SymbolCategory::AmsDelimiters),
    s("⌞", "\\llcorner", SymbolCategory::AmsDelimiters),
    s("⌟", "\\lrcorner", SymbolCategory::AmsDelimiters),
    s("|", "\\lvert", SymbolCategory::AmsDelimiters),
    s("|", "\\rvert", SymbolCategory::AmsDelimiters),
    s("‖", "\\lVert", SymbolCategory::AmsDelimiters),
    s("‖", "\\rVert", SymbolCategory::AmsDelimiters),
    // ── AMS Greek & Hebrew ──
    s("ϝ", "\\digamma", SymbolCategory::AmsGreekHebrew),
    s("ϰ", "\\varkappa", SymbolCategory::AmsGreekHebrew),
    s("ב", "\\beth", SymbolCategory::AmsGreekHebrew),
    s("ד", "\\daleth", SymbolCategory::AmsGreekHebrew),
    s("ג", "\\gimel", SymbolCategory::AmsGreekHebrew),
    // ── AMS binary operators ──
    s("∔", "\\dotplus", SymbolCategory::AmsBinaryOperators),
    s("∖", "\\smallsetminus", SymbolCategory::AmsBinaryOperators),
    s("⋒", "\\Cap", SymbolCategory::AmsBinaryOperators),
    s("⋓", "\\Cup", SymbolCategory::AmsBinaryOperators),
    s("⊼", "\\barwedge", SymbolCategory::AmsBinaryOperators),
    s("⊻", "\\veebar", SymbolCategory::AmsBinaryOperators),
    s("⩎", "\\doublebarwedge", SymbolCategory::AmsBinaryOperators),
    s("⊟", "\\boxminus", SymbolCategory::AmsBinaryOperators),
    s("⊠", "\\boxtimes", SymbolCategory::AmsBinaryOperators),
    s("⊡", "\\boxdot", SymbolCategory::AmsBinaryOperators),
    s("⊞", "\\boxplus", SymbolCategory::AmsBinaryOperators),
    s("⋇", "\\divideontimes", SymbolCategory::AmsBinaryOperators),
    s("⋉", "\\ltimes", SymbolCategory::AmsBinaryOperators),
    s("⋊", "\\rtimes", SymbolCategory::AmsBinaryOperators),
    s("⋋", "\\leftthreetimes", SymbolCategory::AmsBinaryOperators),
    s("⋌", "\\rightthreetimes", SymbolCategory::AmsBinaryOperators),
    s("⋏", "\\curlywedge", SymbolCategory::AmsBinaryOperators),
    s("⋎", "\\curlyvee", SymbolCategory::AmsBinaryOperators),
    s("⊝", "\\circleddash", SymbolCategory::AmsBinaryOperators),
    s("⊛", "\\circledast", SymbolCategory::AmsBinaryOperators),
    s("⊚", "\\circledcirc", SymbolCategory::AmsBinaryOperators),
    s("⋅", "\\centerdot", SymbolCategory::AmsBinaryOperators),
    s("⊺", "\\intercal", SymbolCategory::AmsBinaryOperators),
    // ── AMS binary relations ──
    s("⩽", "\\leqslant", SymbolCategory::AmsBinaryRelations),
    s("⩾", "\\geqslant", SymbolCategory::AmsBinaryRelations),
    s("≲", "\\lesssim", SymbolCategory::AmsBinaryRelations),
    s("≳", "\\gtrsim", SymbolCategory::AmsBinaryRelations),
    s("⪅", "\\lessapprox", SymbolCategory::AmsBinaryRelations),
    s("⪆", "\\gtrapprox", SymbolCategory::AmsBinaryRelations),
    s("≊", "\\approxeq", SymbolCategory::AmsBinaryRelations),
    s("⋖", "\\lessdot", SymbolCategory::AmsBinaryRelations),
    s("⋗", "\\gtrdot", SymbolCategory::AmsBinaryRelations),
    s("⋘", "\\lll", SymbolCategory::AmsBinaryRelations),
    s("⋙", "\\ggg", SymbolCategory::AmsBinaryRelations),
    s("⋚", "\\lesseqgtr", SymbolCategory::AmsBinaryRelations),
    s("⋛", "\\gtreqless", SymbolCategory::AmsBinaryRelations),
    s("≑", "\\doteqdot", SymbolCategory::AmsBinaryRelations),
    s("≖", "\\eqcirc", SymbolCategory::AmsBinaryRelations),
    s("≗", "\\circeq", SymbolCategory::AmsBinaryRelations),
    s("≜", "\\triangleq", SymbolCategory::AmsBinaryRelations),
    s("≓", "\\risingdotseq", SymbolCategory::AmsBinaryRelations),
    s("≒", "\\fallingdotseq", SymbolCategory::AmsBinaryRelations),
    s("∽", "\\backsim", SymbolCategory::AmsBinaryRelations),
    s("≼", "\\preccurlyeq", SymbolCategory::AmsBinaryRelations),
    s("≽", "\\succcurlyeq", SymbolCategory::AmsBinaryRelations),
    s("⋞", "\\curlyeqprec", SymbolCategory::AmsBinaryRelations),
    s("⋟", "\\curlyeqsucc", SymbolCategory::AmsBinaryRelations),
    s("≾", "\\precsim", SymbolCategory::AmsBinaryRelations),
    s("≿", "\\succsim", SymbolCategory::AmsBinaryRelations),
    s("⫅", "\\subseteqq", SymbolCategory::AmsBinaryRelations),
    s("⫆", "\\supseteqq", SymbolCategory::AmsBinaryRelations),
    s("⋐", "\\Subset", SymbolCategory::AmsBinaryRelations),
    s("⋑", "\\Supset", SymbolCategory::AmsBinaryRelations),
    s("⊲", "\\vartriangleleft", SymbolCategory::AmsBinaryRelations),
    s("⊳", "\\vartriangleright", SymbolCategory::AmsBinaryRelations),
    s("⊴", "\\trianglelefteq", SymbolCategory::AmsBinaryRelations),
    s("⊵", "\\trianglerighteq", SymbolCategory::AmsBinaryRelations),
    s("⊨", "\\vDash", SymbolCategory::AmsBinaryRelations),
    s("⊩", "\\Vdash", SymbolCategory::AmsBinaryRelations),
    s("⊪", "\\Vvdash", SymbolCategory::AmsBinaryRelations),
    s("⌣", "\\smallsmile", SymbolCategory::AmsBinaryRelations),
    s("⌢", "\\smallfrown", SymbolCategory::AmsBinaryRelations),
    s("≏", "\\bumpeq", SymbolCategory::AmsBinaryRelations),
    s("≎", "\\Bumpeq", SymbolCategory::AmsBinaryRelations),
    s("≬", "\\between", SymbolCategory::AmsBinaryRelations),
    s("⋔", "\\pitchfork", SymbolCategory::AmsBinaryRelations),
    s("϶", "\\backepsilon", SymbolCategory::AmsBinaryRelations),
    s("∝", "\\varpropto", SymbolCategory::AmsBinaryRelations),
    s("◀", "\\blacktriangleleft", SymbolCategory::AmsBinaryRelations),
    s("▶", "\\blacktriangleright", SymbolCategory::AmsBinaryRelations),
    s("∴", "\\therefore", SymbolCategory::AmsBinaryRelations),
    s("∵", "\\because", SymbolCategory::AmsBinaryRelations),
    // ── AMS arrows ──
    s("⇠", "\\dashleftarrow", SymbolCategory::AmsArrows),
    s("⇢", "\\dashrightarrow", SymbolCategory::AmsArrows),
    s("⇇", "\\leftleftarrows", SymbolCategory::AmsArrows),
    s("⇉", "\\rightrightarrows", SymbolCategory::AmsArrows),
    s("⇆", "\\leftrightarrows", SymbolCategory::AmsArrows),
    s("⇄", "\\rightleftarrows", SymbolCategory::AmsArrows),
    s("⇚", "\\Lleftarrow", SymbolCategory::AmsArrows),
    s("⇛", "\\Rrightarrow", SymbolCategory::AmsArrows),
    s("↞", "\\twoheadleftarrow", SymbolCategory::AmsArrows),
    s("↠", "\\twoheadrightarrow", SymbolCategory::AmsArrows),
    s("↢", "\\leftarrowtail", SymbolCategory::AmsArrows),
    s("↣", "\\rightarrowtail", SymbolCategory::AmsArrows),
    s("↫", "\\looparrowleft", SymbolCategory::AmsArrows),
    s("↬", "\\looparrowright", SymbolCategory::AmsArrows),
    s("⇋", "\\leftrightharpoons", SymbolCategory::AmsArrows),
    s("⇌", "\\rightleftharpoons", SymbolCategory::AmsArrows),
    s("↶", "\\curvearrowleft", SymbolCategory::AmsArrows),
    s("↷", "\\curvearrowright", SymbolCategory::AmsArrows),
    s("↺", "\\circlearrowleft", SymbolCategory::AmsArrows),
    s("↻", "\\circlearrowright", SymbolCategory::AmsArrows),
    s("↰", "\\Lsh", SymbolCategory::AmsArrows),
    s("↱", "\\Rsh", SymbolCategory::AmsArrows),
    s("⇈", "\\upuparrows", SymbolCategory::AmsArrows),
    s("⇊", "\\downdownarrows", SymbolCategory::AmsArrows),
    s("↿", "\\upharpoonleft", SymbolCategory::AmsArrows),
    s("↾", "\\upharpoonright", SymbolCategory::AmsArrows),
    s("⇃", "\\downharpoonleft", SymbolCategory::AmsArrows),
    s("⇂", "\\downharpoonright", SymbolCategory::AmsArrows),
    s("⊸", "\\multimap", SymbolCategory::AmsArrows),
    s("⇝", "\\rightsquigarrow", SymbolCategory::AmsArrows),
    s("↭", "\\leftrightsquigarrow", SymbolCategory::AmsArrows),
    s("↚", "\\nleftarrow", SymbolCategory::AmsArrows),
    s("↛", "\\nrightarrow", SymbolCategory::AmsArrows),
    s("⇍", "\\nLeftarrow", SymbolCategory::AmsArrows),
    s("⇏", "\\nRightarrow", SymbolCategory::AmsArrows),
    s("↮", "\\nleftrightarrow", SymbolCategory::AmsArrows),
    s("⇎", "\\nLeftrightarrow", SymbolCategory::AmsArrows),
];

/// Palette rows for `category`, preserving catalogue order.
pub fn symbols_in(category: SymbolCategory) -> impl Iterator<Item = &'static TexSymbol> {
    TEX_SYMBOLS
        .iter()
        .filter(move |symbol| symbol.category == category)
}
